# docker compose -f docker-compose-dev.yaml up -d --build
# docker compose -f docker-compose-dev.yaml down -v

services:
  catalog_db:
    container_name: catalog-db-dev
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=catalog-db
    restart: always
    ports:
      - "7101:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/

  basket_db:
    container_name: basket-db-dev
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=basket-db
    restart: always
    ports:
      - "7102:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/

  basket_redis:
    container_name: basket-redis-dev
    image: redis
    command: redis-server --requirepass "12345678" --protected-mode no
    restart: always
    ports:
      - "7122:6379"
    volumes:
      - redis_basket:/data

  # promotion grpc
  promotion_db:
    container_name: promotion-db-dev
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=promotion-db
    restart: always
    ports:
      - "7103:3306"
    volumes:
      - mysql_promotion:/var/lib/mysql


volumes:
  postgres_catalog:
  postgres_basket:
  redis_basket:
  mysql_promotion:  