# Собирает Docker-образ из указанного Dockerfile, 
# полностью игнорируя кэш, и присваивает ему тег catalog.api:latest
# docker build --no-cache -t catalog.api:latest -f dockerfile-catalog .

# Выводит список всех сетей, созданных в Docker на вашем хосте
# docker network ls

# docker run -d \
#   --name catalog.api \
#   --network microplace_default \
#   -p 7201:8080 \
#   -e ConnectionStrings__PgConnection="..." \
#   -e MediatR__LicenseKey="..." \
#   catalog.api:latest

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["src/Services/Catalog/Catalog.API/Catalog.API.csproj", "src/Services/Catalog/Catalog.API/"]
COPY ["src/Services/Catalog/Catalog.Application/Catalog.Application.csproj", "src/Services/Catalog/Catalog.Application/"]
COPY ["src/Services/Catalog/Catalog.Domain/Catalog.Domain.csproj", "src/Services/Catalog/Catalog.Domain/"]
COPY ["src/Services/Catalog/Catalog.Infrastructure/Catalog.Infrastructure.csproj", "src/Services/Catalog/Catalog.Infrastructure/"]

RUN dotnet restore "src/Services/Catalog/Catalog.API/Catalog.API.csproj"

COPY . .

RUN dotnet build "src/Services/Catalog/Catalog.API/Catalog.API.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "src/Services/Catalog/Catalog.API/Catalog.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app

COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "Catalog.API.dll"]