# docker compose -f docker-compose-prod.yaml up -d --build
# docker compose -f docker-compose-prod.yaml down -v

services:

  catalog_db:
    container_name: catalog-db-prod
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: catalog-db
    restart: always
    ports:
      - "7411:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/

  catalog_api:
    container_name: catalog-api
    build:
      context: .
      dockerfile: ./dockerfile-catalog
      args:
        - BUILDKIT_INLINE_CACHE=0
    ports:
      - "7301:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - catalog_db
    restart: unless-stopped

# basket.api

  basket_db:
    container_name: basket-db-prod
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: basket-db
    restart: always
    ports:
      - "7412:5432"
    volumes:
      - postgres_basket_prod:/var/lib/postgresql/

  basket_redis:
    container_name: basket-redis-prod
    image: redis
    command: redis-server --requirepass "12345678" --protected-mode no
    restart: always
    ports:
      - "7422:6379"
    volumes:
      - redis_basket_prod:/data

  basket_api:
    container_name: basket-api
    build:
      context: .
      dockerfile: ./dockerfile-basket
      args:
        - BUILDKIT_INLINE_CACHE=0
    ports:
      - "7302:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - basket_db
      - basket_redis  
    restart: unless-stopped

volumes:
  postgres_catalog:
  postgres_basket_prod:
  redis_basket_prod:
